FROM ubuntu:latest

RUN apt-get update && apt-get install -y python3 python3-pip

COPY ./utils/requirements.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

COPY ./utils /app/utils

CMD ["python3", "/app/utils/server.py"]