version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=movie-app
    ports:
      - '5432:5432'

  spring:
    container_name: movie-app
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/movie-app
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    depends_on:
      - psql-db
  
  scrape:
    container_name: flask-app
    build:
      context: .
      dockerfile: Dockerfile.scrape
    ports:
      - '5000:5000'

  client:
    container_name: client-app
    build:
      context: ../../client/movie-client/
      dockerfile: Dockerfile.client
    ports:
      - '5173:5173'
